sample/sample1/sample/config/routes.rb
Rails.application.routes.draw do
  resources :projects

  devise_for :users

   root 'projects#index'

end

sample/sample1/sample/app/models/ability.rb
class Ability
	include CanCan::Ability

	def initialize(user)
		# Define abilities for the passed in user here. For example:
		#
		user ||= User.new # guest user (not logged in)
		if user_signed_in?
			if user.admin?
				can :manage, :all
			end
		else
			can :read, :all
		end
		#
		# The first argument to `can` is the action you are giving the user 
		# permission to do.
		# If you pass :manage it will apply to every action. Other common actions
		# here are :read, :create, :update and :destroy.
		#
		# The second argument is the resource the user can perform the action on. 
		# If you pass :all it will apply to every resource. Otherwise pass a Ruby
		# class of the resource.
		#
		# The third argument is an optional hash of conditions to further filter the
		# objects.
		# For example, here the user can only update published articles.
		#
		#   can :update, Article, :published => true
		#
		# See the wiki for details:
		# https://github.com/ryanb/cancan/wiki/Defining-Abilities
	end
end

sample/sample1/sample/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  def add_details(id,name)
	  self.user_id=id
	  self.owner_name=name
    end
end

sample/sample1/sample/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects,:dependent => :destroy

end

sample/sample1/sample/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth) }
  end
end

sample/sample1/sample/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
	id=current_user.id

    @projects = Project.where(user_id:id)
    @others=Project.where("user_id!=?",id)

end


  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    if @project.user_id!=current_user.id
      flash[:notice]="insufficient privilleges"
        redirect_to "/projects"

       end
  end

  # POST /projects
  # POST /projects.json
  def create
    if user_signed_in?
    @project = Project.new(project_params)	
    @project.add_details(current_user.id,User.find(current_user.id).email)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
    else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update

    if @project.user_id=current_user.id
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
    else
      format.html { render :index }
      format.json { render json: @project.errors, status: :unprocessable_entity , notice: 'No  required permissions.'}
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    if @project.user_id=current_user.id

    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
    else
      format.html { render :index }
      format.json { render json: @project.errors, status: :unprocessable_entity , notice: 'No  required permissions.'}
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :owner_name, :user_id)
    end
end

sample/sample1/sample/app/helpers/application_helper.rb
module ApplicationHelper
end

sample/sample1/sample/app/helpers/projects_helper.rb
module ProjectsHelper
end

sample/sample1/sample/app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <%= value %>
    </div>
<% end %>

sample/sample1/sample/app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "projects", root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Posts', '#' %></li>
        <% if current_user %>
            <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

sample/sample1/sample/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
	  <% end %>
	  <% if alert %>
		    <p class="alert alert-danger"><%= alert %></p>
	    <% end %>
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
<%= yield %>

</body>
</html>

sample/sample1/sample/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sample/sample1/sample/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

sample/sample1/sample/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Your Projects</h1>

<% if @projects!=nil %>
    <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.owner_name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
       </tbody>
</table>
<br>
<%else %>
<p> No Projects to Show </p>
    <%end%>
<h1>Listing Others Projects</h1>

<% if @others!=nil %>
    <table>
      <thead>
      <tr>
        <th>Name</th>
        <th>Owner name</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @others.each do |project| %>
          <tr>
            <td><%= project.name %></td>
            <td><%= project.owner_name %></td>
            <td><%= link_to 'Show', project %></td>
            </tr>
      <% end %>
      </tbody>
    </table>
    <br>
<%else %>
    <p> No Projects to Show </p>
<%end%>
<%= link_to 'New Project', new_project_path %>

sample/sample1/sample/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

sample/sample1/sample/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Owner name:</strong>
  <%= @project.owner_name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

sample/sample1/sample/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>