sample/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :comments
  resources :projects do
	  resources :issues do
      resources :comments
    end
  end
  devise_for :users

   root 'projects#index'

end

sample/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :issue
  validates :commenter, :presence => true
  validates :body, :presence => true
end

sample/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    #@comments = Comment.all
    issue=Issue.find(params[:issue_id])
    @comments=issue.comments
    respond_to do |format|
      format.html
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    issue=Issue.find(params[:issue_id])
    comment=issue.comments.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  # GET /comments/new
  def new
    #@comment = Comment.new
    issue=Issue.find(params[:issue_id])

    @comment=issue.comments.build
    respond_to do |format|
      format.html
    end
  end

  # GET /comments/1/edit
  def edit
    issue=Issue.find(params[:issue_id])
    @comment=issue.comments.find(params[:id])
    if current_user.id != issue.user_id
      flash[:notice]="Only issue owner can Remove/edit comments"
      flash[:color]="Invalid"
      redirect_to([@comment.issue.project ,@comment.issue])
    end
  end

  # POST /comments
  # POST /comments.json
  def create
   # @comment = Comment.new(comment_params)
    issue=Issue.find(params[:issue_id])
    @comment=issue.comments.create(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@comment.issue.project ,@comment.issue,@comment], :notice => 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :action =>"new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    issue=Issue.find(params[:issue_id])
    @comment=issue.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to ([issue.project,issue]),  :notice => 'Comment was successfully updated.' }
        format.json { render :show, :status => :ok, location: @comment }
      else
        format.html { render :action =>"edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    issue=Issue.find(params[:issue_id])
    if current_user.id == issue.user_id
      @comment=issue.comments.find(params[:id])
        @comment.destroy
    respond_to do |format|
      format.html { redirect_to([issue.project,issue])}
      format.json { head :ok }
    end
    else
      flash[:notice]="Only issue owner can Remove/edit comments"
      flash[:color]="Invalid"
      redirect_to ([issue.project,issue])
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:commenter, :body, :issue_id)
    end
end

sample/app/helpers/comments_helper.rb
module CommentsHelper
end

sample/app/views/comments/_form.html.erb
<%= form_for [@comment.issue.project ,@comment.issue,@comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter ,:readonly => :true , :value => :"#{current_user.email}" %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :issue_id %><br>
    <%= f.text_field :issue_id ,:readonly => :true%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sample/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', [@comment.issue.project, @comment.issue ]%>

sample/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Commenter</th>
      <th>Body</th>
      <th>Issue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commenter %></td>
        <td><%= comment.body %></td>
        <td><%= comment.issue %></td>
        <td><%= link_to 'Show', [comment.issue.project ,comment.issue,comment] %></td>
        <td><%= link_to 'Edit', edit_project_issue_comment_path(comment.issue.project,comment.issue,comment) %></td>
        <td><%= link_to 'Destroy', [comment.issue.project ,comment.issue,comment], :method => :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

sample/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form',:issue_id => :@issue_id%>

<%= link_to 'Back', [@comment.issue.project, @comment.issue ]%>

sample/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commenter:</strong>
  <%= @comment.commenter %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Back', [@comment.issue.project, @comment.issue ]%>