sample/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :comments
  resources :projects do
	  resources :issues do
      resources :comments
    end
  end
  devise_for :users

   root 'projects#index'

end

sample/app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :comments
  def add_details(email,name,id,userid)
    self.issued_by=email
    self.project_name=name
    self.project_id=id
    self.user_id=userid
  end
end

sample/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    project=Project.find(params[:project_id])

    @issues = project.issues
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    project=Project.find(params[:project_id])

    @issue = project.issues.find(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @issue }
    end
  end

  # GET /issues/new
  def new
    project=Project.find(params[:project_id])
    @project_id=params[:project_id]
    @issue=project.issues.build
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @issue }
  end
  end
  # GET /issues/1/edit
  def edit

    project=Project.find(params[:project_id])
    @issue = project.issues.find(params[:id])
    if @issue.user_id!=current_user.id
      flash[:notice]="No privilleges to edit"
      flash[:color]='invalid'
      redirect_to "/projects/#{project.id}/issues"

  end
  end

  # POST /issues
  # POST /issues.json
  def create
    if user_signed_in?
       project=Project.find(params[:project_id])
       @issue = project.issues.create(issue_params)
      email=current_user.email
      @issue.add_details(email,project.name,project.id,current_user.id)
     respond_to do |format|
      if @issue.save
        format.html { redirect_to [@issue.project,@issue, notice: 'Issue was successfully created.'] }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :action => "new"}
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
    else
      flash[:notice]="Signup or log in to create as issue"
      flash[:color]="invalid"
      redirect_to "/projects"
    end

  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    project = Project.find(params[:project_id])
    #2nd you retrieve the comment thanks to params[:id]
    @issue = project.issues.find(params[:id])
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to([@issue.project, @issue], :notice => 'issue was successfully updated.') }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :action => "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    project = Project.find(params[:project_id])
    @issue = project.issues.find(params[:id])
    if @issue.user_id==current_user.id or project.user_id==current_user.id
      puts"\n\n\n #{@issue.user_id}  #{project.user_id}   #{current_user.id}\n\n\n"
      @issue.destroy
   respond_to do |format|
      format.html { redirect_to(project_issues_url) }
      format.xml  { head :ok }
   end
  else
    flash[:notice]="No privilleges to delete"
    flash[:color]='invalid'
    redirect_to "/projects/#{project.id}/issues"
  end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:subject, :description, :issued_by, :project_name, :project_id, :user_id)
    end
end

sample/app/helpers/issues_helper.rb
module IssuesHelper
end

sample/app/views/issues/_form.html.erb
<%= form_for([@issue.project,@issue]) do |f| %>
	<% if @issue.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

			<ul>
				<% @issue.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :subject %><br>
		<%= f.text_field :subject %>
	</div>
	<div class="field">
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</div>
	<div class="field">
		<%= f.label :project_id %><br>
		<%= f.text_field :project_id ,:readonly => true %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

sample/app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form' %>

<%= link_to 'Show', [@issue.project, @issue] %> |
<%= link_to 'Back', project_issues_path(@issue.project) %>

sample/app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Issues</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Issued by</th>
      <th>Project name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.subject %></td>
        <td><%= issue.issued_by %></td>
        <td><%= issue.project_name %></td>
        <td><%= link_to 'Show', [issue.project, issue] %></td>
        <td><%= link_to 'Edit', edit_project_issue_path(issue.project, issue)%></td>
        <td><%= link_to 'Destroy', [issue.project, issue], data:{ confirm: 'Are you sure?' }, :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', {:action => :new,} %>

sample/app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form',:project_id => :@project_id %>

<%= link_to 'Back', "/projects/#{@project_id}/issues" %>

sample/app/views/issues/show.html.erb
<h1 style="text-align:center">Issue <%="#{@issue.subject}" %></h1>

<p>
  <strong>Description:</strong>
  <%= @issue.description %>
</p>

<p>
  <strong>Issued by:</strong>
  <%= @issue.issued_by %>
</p>

<p>
  <strong>Project name:</strong>
  <%= @issue.project_name %>
</p>

<h2>Comments </h2>
<% @issue.comments.each do |comment| %>
    <p>
      <strong>
        Commenter
      </strong>
      <%= comment.commenter %>
    </p>
    <p>
      <strong>
        Body
      </strong>
      <%= comment.body %>
    </p>
    <%= link_to 'Edit', edit_project_issue_comment_path(comment.issue.project,comment.issue,comment) %>|
    <%= link_to 'Destroy', [comment.issue.project ,comment.issue,comment], :method => :delete, data: { confirm: 'Are you sure?' } %></p>

<% end%>

<%= link_to 'Edit', edit_project_issue_path(@issue.project, @issue) %>
<%= link_to 'Back', project_issues_path(@issue.project) %>
<%= link_to 'Keep Comment',{ :controller => :comments ,:action => :new,  :issue=> @issue ,:issue_id => @issue.id ,} %>